
# Syntax highlighting
highlighter:         rouge

# Permalinks
permalink:           /:title


# Setup
timezone:            Asia/Jakarta
locale:              id
name:				         
title:               Ekky Pramana Personal Blog
tagline:             'You should not take this too seriously.'
description:         'Personal blog of Ekky Pramana'
url:
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/img/icon.png
disqus:              ekkypramana

author:
  name:           	 Ekky
  url:            	 http://blog.ekkypramana.com
  facebook:          ekkypramana
  twitter:           ekkyvalent
  gplus:             +EkkyPramana
  instagram:         ekkyvalent
  snapchat:          ekkyvalent
  soundcloud:        ekkyvalent
  steam:             evale

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
